---

- hosts: master
  remote_user: vagrant
  become: yes
  roles:
    - postgresql_master
  tags: master

- hosts: slaves
  remote_user: vagrant
  become: yes
  roles:
    - postgresql_slave
  tags: slave
