---

- name: POSTGRESQL | Create directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: "{{ postgres_archive_directory }}", owner: "postgres", group: "postgres", mode: "0755" }
  
- name: POSTGRESQL | Configuration
  template:
    src: "etc/postgresql/{{ postgres_version }}/main/postgresql.conf.j2"
    dest: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    owner: postgres
    group: postgres
    mode: 0644
  notify: reload postgresql
  tags: config

- name: POSTGRESQL | Create replication user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ postgres_replication_user }}"
    encrypted: yes
    password: "md5{{ (postgres_replication_password + postgres_replication_user)|hash('md5') }}"
    role_attr_flags: REPLICATION
    state: present
