---

- name: POSTGRESQL | Check configuration
  stat:
    path: "{{ postgres_data_directory }}"
  register: data

- name: POSTGRESQL | Secure
  import_tasks: secure.yml
  tags: secure

- name: POSTGRESQL | Migrate
  import_tasks: migrate.yml
  when: not data.stat.exists
  tags: migrate

- name: POSTGRESQL | Configure
  import_tasks: configure.yml
  tags: configure
