---

- name: POSTGRESQL | Ensure Postgres is stopped
  systemd:
    name: postgresql
    state: stopped

- name: POSTGRESQL | Create directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: "{{ postgres_data_directory }}", owner: "postgres", group: "postgres", mode: "0700" }

- name: POSTGRESQL | Migrate data directory
  command: cp -aRv /var/lib/postgresql/{{ postgres_version }}/main {{ postgres_data_directory }}

- name: POSTGRESQL | Ensure Postgres is started
  systemd:
    name: postgresql
    state: started
