---

- name: POSTGRESQL | Security
  template:
    src: "etc/postgresql/{{ postgres_version }}/main/pg_hba.conf.j2"
    dest: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0644
  notify: restart postgresql
