---

- name: POSTGRESQL | Configuration
  template:
    src: "etc/postgresql/{{ postgres_version }}/main/postgresql.conf.j2"
    dest: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    owner: postgres
    group: postgres
    mode: 0644
  notify: reload postgresql
  tags: config

- name: POSTGRESQL | Check configuration
  stat:
    path: "/etc/postgresql/{{ postgres_version }}/main/recovery.conf"
  register: init_slave

- name: POSTGRESQL | Run base backup
  become: yes
  become_user: postgres
  command: /usr/bin/pg_basebackup -h {{ groups['master'][0] }} -U {{ postgres_replication_user }} -D {{ postgres_data_directory }} -P --xlog
  environment:
    - PGPASSWORD: "{{ postgres_replication_password }}"
  notify: restart postgresql
  when: not init_slave.stat.exists

- name: POSTGRESQL | Deploy recovery file
  template:
    src: "etc/postgresql/{{ postgres_version }}/main/recovery.conf.j2"
    dest: "/etc/postgresql/{{ postgres_version }}/main/recovery.conf"
    owner: postgres
    group: postgres
    mode: 0600
  notify: restart postgresql
  when: not init_slave.stat.exists
