---

- name: POSTGRESQL | Check configuration
  stat:
    path: "{{ postgres_archive_directory }}"
  register: archive

- name: POSTGRESQL | Secure
  import_tasks: secure.yml
  tags: secure

- name: POSTGRESQL | Migrate
  import_tasks: migrate.yml
  when: not archive.stat.exists
  tags: migrate

- name: POSTGRESQL | Configure
  import_tasks: configure.yml
  tags: configure
