---

- name: POSTGRESQL | Ensure Postgres is stopped
  systemd:
    name: postgresql
    state: stopped

- name: POSTGRESQL | Delete default data directory
  file:
    path: /var/lib/postgresql/{{ postgres_version }}/main
    state: absent
  when: not archive.stat.exists

- name: POSTGRESQL | Create directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: "{{ postgres_data_directory }}", owner: "postgres", group: "postgres", mode: "0700" }
